# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd1302a3330358aa079e566488c53e7cfeea0d547a38e63574eaa5b3b2ae6df70835488beb75087b92cbdc1b77579801768ddf5cc7d1f2c81e133cab23610f97

test:
  secret_key_base: 77ea7f1dd6264fe9beb091c5df2df9ef95388783f5021a5bfb87a587a6d3d5794f1bf30cb9693a27edf5cc5ffd9669790bcd53eba0e03d0616b6b071bbac5863

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
